# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LED_Design/heisserDraht.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mw_draht(object):
    def setupUi(self, mw_draht):
        mw_draht.setObjectName("mw_draht")
        mw_draht.setWindowModality(QtCore.Qt.NonModal)
        mw_draht.resize(1680, 1000)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mw_draht.sizePolicy().hasHeightForWidth())
        mw_draht.setSizePolicy(sizePolicy)
        mw_draht.setMinimumSize(QtCore.QSize(1680, 1000))
        mw_draht.setAutoFillBackground(True)
        mw_draht.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(mw_draht)
        self.centralwidget.setObjectName("centralwidget")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(30, 120, 1061, 341))
        font = QtGui.QFont()
        font.setFamily("Tlwg Typo")
        font.setPointSize(36)
        font.setItalic(True)
        self.lcdNumber.setFont(font)
        self.lcdNumber.setAutoFillBackground(False)
        self.lcdNumber.setStyleSheet("QLCDNumber {color: green;}")
        self.lcdNumber.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lcdNumber.setFrameShape(QtWidgets.QFrame.Box)
        self.lcdNumber.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcdNumber.setLineWidth(8)
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setDigitCount(8)
        self.lcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdNumber.setProperty("intValue", 0)
        self.lcdNumber.setObjectName("lcdNumber")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(370, 10, 1001, 91))
        font = QtGui.QFont()
        font.setPointSize(72)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(40, 470, 1201, 331))
        self.graphicsView.setObjectName("graphicsView")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(1170, 160, 421, 241))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber_2.setGeometry(QtCore.QRect(220, 0, 281, 101))
        font = QtGui.QFont()
        font.setFamily("Tlwg Typo")
        font.setPointSize(36)
        font.setItalic(True)
        self.lcdNumber_2.setFont(font)
        self.lcdNumber_2.setAutoFillBackground(False)
        self.lcdNumber_2.setStyleSheet("QLCDNumber {color: red;}")
        self.lcdNumber_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lcdNumber_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumber_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcdNumber_2.setLineWidth(8)
        self.lcdNumber_2.setSmallDecimalPoint(False)
        self.lcdNumber_2.setDigitCount(2)
        self.lcdNumber_2.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdNumber_2.setProperty("intValue", 55)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 301, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 110, 401, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.groupBox.raise_()
        self.lcdNumber.raise_()
        self.label.raise_()
        self.graphicsView.raise_()
        mw_draht.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mw_draht)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1680, 29))
        self.menubar.setObjectName("menubar")
        mw_draht.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mw_draht)
        self.statusbar.setObjectName("statusbar")
        mw_draht.setStatusBar(self.statusbar)

        self.retranslateUi(mw_draht)
        QtCore.QMetaObject.connectSlotsByName(mw_draht)

    def retranslateUi(self, mw_draht):
        _translate = QtCore.QCoreApplication.translate
        mw_draht.setWindowTitle(_translate("mw_draht", "heißerDraht"))
        self.label.setText(_translate("mw_draht", "Der heiße Draht!"))
        self.label_2.setText(_translate("mw_draht", "Berührungen:"))
        self.label_3.setText(_translate("mw_draht", "TextLabel"))
